apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secret-inject
  name: secret-inject
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: secret-inject
  template:
    metadata:
      labels:
        app: secret-inject
    spec:
      volumes:
      - name: certs
        secret:
          secretName: secret-inject-tls
      containers:
      - name: secret-inject-init
        image: erousseau/aws-secrets-injector-adm-controller:latest
        volumeMounts:
        - name: certs
          mountPath: /tls
          readOnly: true
        args:
        - --tls-cert-file=/tls/tls.crt
        - --tls-private-key-file=/tls/tls.key
        - --init-container-image=erousseau/aws-secrets-injector-init-container:latest
        ports:
        - containerPort: 443
        imagePullPolicy: Always
